apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: credentials.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  names:
    kind: Credential
    plural: credentials
    shortNames:
    - creds
    singular: credential
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true