apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databaseservers.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  names:
    kind: DatabaseServer
    plural: databaseservers
    shortNames:
    - dbms
    singular: databaseserver
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              observedGeneration:
                type: integer
            type: object
          spec:
            properties:
              ServiceSelector:
                properties:
                  matchExpressions:
                    items:
                    - properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                          - type: string
                          type: array
                      type: object
                    type: array
                  matchLabels:
                    type: object
                type: object
              AdminUserName:
                type: string
              AdminPasswordSecret:
                properties:
                  Value:
                    type: string
                  SecretKeyRef:
                    properties:
                      key:
                        type: string
                      name:
                        type: string
                      optional:
                        type: boolean
                    type: object
                type: object
              ServiceUrl:
                type: string
            type: object
        type: object
    served: true
    storage: true