apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databaseservers.mssql-operator.github.io
spec:
  group: mssql-operator.github.io
  names:
    kind: DatabaseServer
    plural: databaseservers
    shortNames:
    - dbms
    singular: databaseserver
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true