apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  names:
    kind: Database
    plural: databases
    shortNames:
    - db
    singular: database
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true