apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deploymentscripts.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  names:
    kind: DeploymentScript
    plural: deploymentscripts
    shortNames:
    - script
    singular: deploymentscript
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              LastUpdate:
                type: string
              Reason:
                type: string
              Message:
                type: string
              ExecutedDate:
                type: string
              observedGeneration:
                type: integer
            type: object
          spec:
            properties:
              DatabaseSelector:
                properties:
                  matchExpressions:
                    items:
                    - properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                          - type: string
                          type: array
                      type: object
                    type: array
                  matchLabels:
                    type: object
                type: object
              Script:
                type: string
            type: object
        type: object
    served: true
    storage: true