apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deploymentscripts.mssql-operator.github.io
spec:
  group: mssql-operator.github.io
  names:
    kind: DeploymentScript
    plural: deploymentscripts
    shortNames:
    - script
    singular: deploymentscript
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true