apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databases.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  names:
    kind: Database
    plural: databases
    shortNames:
    - db
    singular: database
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              LastUpdate:
                type: string
              Reason:
                type: string
              Message:
                type: string
              observedGeneration:
                type: integer
            type: object
          spec:
            properties:
              DatabaseSelector:
                properties:
                  matchExpressions:
                    items:
                    - properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                          - type: string
                          type: array
                      type: object
                    type: array
                  matchLabels:
                    type: object
                type: object
              Collation:
                type: string
              LogFiles:
                items:
                - properties:
                    Name:
                      type: string
                    Path:
                      type: string
                    IsPrimaryFile:
                      type: boolean
                  type: object
                type: array
              BackupFiles:
                items:
                - properties:
                    Name:
                      type: string
                    Path:
                      type: string
                    IsPrimaryFile:
                      type: boolean
                  type: object
                type: array
              DataFiles:
                type: object
              GCStrategy:
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}