apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: databases
    singular: database
    kind: Database
    shortNames:
    - db