apiVersion: v1
kind: ServiceAccount
metadata:
  name: mssql-operator-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mssql-operator-clusterrole
rules:
- apiGroups:
  - "mssql.techpyramid.ws"
  resources:
  - databases
  - databaseservers
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: mssql-operator-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mssql-operator-clusterrole
subjects:
- kind: ServiceAccount
  name: mssql-operator-serviceaccount
  namespace: default