apiVersion: mssql.techpyramid.ws/v1alpha1
kind: DatabaseServer
metadata:
  name: techpyramid-dev
  namespace: "default"
  labels:
    database-server: dev
spec:
  #serviceUrl: localhost,1433
  serviceSelector:
    matchLabels:
      tier: db
  adminUserName: sa
  adminPasswordSecret:
    secretKeyRef:
      name: mssql
      key: SA_PASSWORD
---
apiVersion: mssql.techpyramid.ws/v1alpha1
kind: Credential
metadata:
  name: techpyramid-azure-backup-credentials
  namespace: default
  labels:
    database-server: dev
spec:
  credentialName: "backups"
  identity: "techpyramidsqlbak"
  secret:
    secretKeyRef:
      name: azure
      key: sas_key
  databaseSelector:
    matchLabels:
      database-server: dev