apiVersion: mssql.techpyramid.ws/v1alpha1
kind: Database
metadata:
  name: "authentication"
  namespace: "default"
  labels:
    database-server: dev
spec:
  databaseSelector:
    matchLabels:
      database-server: dev
  datafiles:
    primary:
      - name: "Authentication"
      - path: /var/opt/mssql/data/Authentication.mdf
  logfiles:
    - name: "Authentication_log"
    - path: /var/opt/mssql/data/Authentication_log.ldf
---
apiVersion: mssql.techpyramid.ws/v1alpha1
kind: Database
metadata:
  name: "accounts"
  namespace: "default"
  labels:
    database-server: dev
spec:
  databaseSelector:
    matchLabels:
      database-server: dev
  datafiles:
    primary:
      - name: "Accounts"
      - path: /var/opt/mssql/data/Accounts.mdf
  logfiles:
    - name: "Accounts_log"
    - path: /var/opt/mssql/data/Accounts_log.ldf
  collation: "default"