apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: DatabaseServers.mssql.techpyramid.ws
spec:
  group: mssql.techpyramid.ws
  names:
    kind: DatabaseServer
    plural: DatabaseServers
    shortNames:
    - dbms
    singular: databaseserver
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}